language: node_js
node_js: node
dist: trusty
sudo: false
install:
  - npm install -g bower purescript pulp
  - npm install pouchdb
script:
  - bower install --production
  - pulp build
  - bower install
  - pulp test
after_success:
  - test $TRAVIS_TAG &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push
