language: node_js
node_js: node
dist: trusty
sudo: required
install:
  - npm install -g bower purescript pulp
  - npm install pouchdb@6.4.2
script:
  - bower install
  - make test
after_success:
  - test $TRAVIS_TAG &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push
